import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

type ReasoningEffort = "medium" | "high" | "xhigh" | "max";

interface Capability {
  model: string;
  reasoningEffort: ReasoningEffort;
}

interface RoleSpec {
  behavior: string;
  description: string;
  defaultCapability: string;
  capabilities: string[];
}

interface AgentRoleSpec {
  version: 1;
  capabilities: Record<string, Capability>;
  routes: Record<string, string>;
  nativeRoleAliases: Record<string, string>;
  roles: RoleSpec[];
}

export interface GeneratedAgentDefinition {
  agentType: string;
  behavior: string;
  capability: string;
  model: string;
  reasoningEffort: ReasoningEffort;
  description: string;
  configFile: string;
}

interface GeneratedAgentsManifest {
  version: 1;
  routes: Record<string, string>;
  nativeRoleAliases: Record<string, string>;
  agents: GeneratedAgentDefinition[];
}

const SPEC_PATH = "assets/agent-role-spec.json";
const TEMPLATE_PATH = "assets/agent-role-templates";
const GENERATED_PATH = "assets/agents";
const IDENTIFIER_PATTERN = /^[a-z][a-z0-9_]*$/;
const REASONING_EFFORTS = new Set<ReasoningEffort>(["medium", "high", "xhigh", "max"]);

export class AgentRolePackagingError extends Error {}

export async function renderAgentRoles(repoRoot = defaultRepoRoot()): Promise<Map<string, string>> {
  const root = resolve(repoRoot);
  const spec = await readSpec(join(root, SPEC_PATH));
  const files = new Map<string, string>();
  const manifest: GeneratedAgentsManifest = {
    version: 1,
    routes: spec.routes,
    nativeRoleAliases: spec.nativeRoleAliases,
    agents: [],
  };
  const seenAgentTypes = new Set<string>();

  for (const role of spec.roles) {
    const templatePath = join(root, TEMPLATE_PATH, `${role.behavior}.toml`);
    const template = await readFile(templatePath, "utf8").catch(() => {
      throw new AgentRolePackagingError(`Missing agent role template: ${templatePath}`);
    });
    const templateConfig = parseTemplate(template, templatePath);
    if (Object.hasOwn(templateConfig, "model") || Object.hasOwn(templateConfig, "model_reasoning_effort")) {
      throw new AgentRolePackagingError(`Agent role template must not select capability: ${templatePath}`);
    }
    if (!role.capabilities.includes(role.defaultCapability)) {
      throw new AgentRolePackagingError(`Default capability is not enabled for ${role.behavior}`);
    }

    for (const capabilityName of role.capabilities) {
      const capability = spec.capabilities[capabilityName];
      if (!capability) throw new AgentRolePackagingError(`Unknown capability ${capabilityName} for ${role.behavior}`);
      const agentType = capabilityName === role.defaultCapability
        ? role.behavior
        : `${role.behavior}_${capabilityName}`;
      if (seenAgentTypes.has(agentType)) throw new AgentRolePackagingError(`Duplicate generated agent type: ${agentType}`);
      seenAgentTypes.add(agentType);
      const configFile = `${agentType}.toml`;
      const description = capabilityName === role.defaultCapability
        ? `${role.description} Default capability: ${capability.model} at ${capability.reasoningEffort} effort.`
        : `${role.description} Capability variant: ${capability.model} at ${capability.reasoningEffort} effort.`;
      files.set(configFile, [
        "# Generated by `bun run agents:build`; edit the role template or capability spec instead.",
        `model = ${JSON.stringify(capability.model)}`,
        `model_reasoning_effort = ${JSON.stringify(capability.reasoningEffort)}`,
        template.trim(),
        "",
      ].join("\n"));
      manifest.agents.push({
        agentType,
        behavior: role.behavior,
        capability: capabilityName,
        model: capability.model,
        reasoningEffort: capability.reasoningEffort,
        description,
        configFile,
      });
    }
  }

  for (const [route, capability] of Object.entries(spec.routes)) {
    if (!spec.capabilities[capability]) throw new AgentRolePackagingError(`Route ${route} uses unknown capability ${capability}`);
  }
  for (const [alias, target] of Object.entries(spec.nativeRoleAliases)) {
    if (seenAgentTypes.has(alias)) {
      throw new AgentRolePackagingError(`Native role alias ${alias} collides with generated agent type`);
    }
    if (!seenAgentTypes.has(target)) {
      throw new AgentRolePackagingError(`Native role alias ${alias} targets unknown generated agent type ${target}`);
    }
  }
  files.set("manifest.json", `${JSON.stringify(manifest, null, 2)}\n`);
  return files;
}

export async function buildAgentRoles(repoRoot = defaultRepoRoot()): Promise<void> {
  const root = resolve(repoRoot);
  const destination = join(root, GENERATED_PATH);
  const files = await renderAgentRoles(root);
  await rm(destination, { force: true, recursive: true });
  await mkdir(destination, { recursive: true });
  await Promise.all([...files].map(([path, contents]) => writeFile(join(destination, path), contents)));
}

export async function checkAgentRoles(repoRoot = defaultRepoRoot()): Promise<void> {
  const root = resolve(repoRoot);
  const destination = join(root, GENERATED_PATH);
  const expected = await renderAgentRoles(root);
  const actualNames = await readdir(destination).catch(() => [] as string[]);
  const differences: string[] = [];
  for (const [path, contents] of expected) {
    const actual = await readFile(join(destination, path), "utf8").catch(() => undefined);
    if (actual === undefined) differences.push(`missing ${path}`);
    else if (actual !== contents) differences.push(`changed ${path}`);
  }
  for (const path of actualNames) {
    if (!expected.has(path)) differences.push(`unexpected ${path}`);
  }
  if (differences.length > 0) {
    throw new AgentRolePackagingError(
      `Generated agent roles diverge from their specification:\n${differences.map((line) => `- ${line}`).join("\n")}\nRun \`bun run agents:build\`.`,
    );
  }
}

async function readSpec(path: string): Promise<AgentRoleSpec> {
  const spec = JSON.parse(await readFile(path, "utf8")) as AgentRoleSpec;
  if (
    spec.version !== 1 ||
    !isRecord(spec.capabilities) ||
    !isRecord(spec.routes) ||
    !isRecord(spec.nativeRoleAliases) ||
    !Array.isArray(spec.roles)
  ) {
    throw new AgentRolePackagingError(`Invalid agent role specification: ${path}`);
  }
  for (const [name, capability] of Object.entries(spec.capabilities)) {
    assertIdentifier(name, `capability ${name}`);
    if (typeof capability.model !== "string" || capability.model.length === 0 || !REASONING_EFFORTS.has(capability.reasoningEffort)) {
      throw new AgentRolePackagingError(`Invalid capability ${name} in ${path}`);
    }
  }
  for (const [route, capability] of Object.entries(spec.routes)) {
    assertIdentifier(route, `route ${route}`);
    assertIdentifier(capability, `route capability ${capability}`);
  }
  for (const [alias, target] of Object.entries(spec.nativeRoleAliases)) {
    assertIdentifier(alias, `native role alias ${alias}`);
    assertIdentifier(target, `native role alias target ${target}`);
  }
  const seenBehaviors = new Set<string>();
  for (const role of spec.roles) {
    assertIdentifier(role.behavior, `role behavior ${role.behavior}`);
    if (seenBehaviors.has(role.behavior)) throw new AgentRolePackagingError(`Duplicate role behavior: ${role.behavior}`);
    seenBehaviors.add(role.behavior);
    if (typeof role.description !== "string" || role.description.length === 0) {
      throw new AgentRolePackagingError(`Invalid description for role ${role.behavior}`);
    }
    assertIdentifier(role.defaultCapability, `default capability ${role.defaultCapability}`);
    if (!Array.isArray(role.capabilities) || role.capabilities.length === 0 || new Set(role.capabilities).size !== role.capabilities.length) {
      throw new AgentRolePackagingError(`Invalid capability list for role ${role.behavior}`);
    }
    role.capabilities.forEach((capability) => assertIdentifier(capability, `role capability ${capability}`));
  }
  return spec;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function assertIdentifier(value: unknown, label: string): asserts value is string {
  if (typeof value !== "string" || !IDENTIFIER_PATTERN.test(value)) {
    throw new AgentRolePackagingError(`Invalid ${label}; expected a lowercase identifier`);
  }
}

function parseTemplate(template: string, path: string): Record<string, unknown> {
  try {
    return Bun.TOML.parse(template) as Record<string, unknown>;
  } catch {
    throw new AgentRolePackagingError(`Invalid agent role template TOML: ${path}`);
  }
}

function defaultRepoRoot(): string {
  return resolve(dirname(fileURLToPath(import.meta.url)), "../../..");
}

async function main(): Promise<void> {
  const command = process.argv[2];
  if (command === "build") await buildAgentRoles();
  else if (command === "check") await checkAgentRoles();
  else throw new AgentRolePackagingError("usage: bun packages/core/src/agent-role-package.ts <build|check>");
}

if (import.meta.main) {
  main().catch((error) => {
    console.error(error instanceof Error ? error.message : "agent role packaging failed");
    process.exit(1);
  });
}
