import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

interface RoleSpec {
  behavior: string;
  description: string;
}

interface AgentRoleSpec {
  version: 1;
  nativeRoleAliases: Record<string, string>;
  roles: RoleSpec[];
}

export interface GeneratedAgentDefinition {
  agentType: string;
  behavior: string;
  description: string;
  configFile: string;
}

interface GeneratedAgentsManifest {
  version: 1;
  nativeRoleAliases: Record<string, string>;
  agents: GeneratedAgentDefinition[];
}

const SPEC_PATH = "assets/agent-role-spec.json";
const TEMPLATE_PATH = "assets/agent-role-templates";
const GENERATED_PATH = "assets/agents";
const IDENTIFIER_PATTERN = /^[a-z][a-z0-9_]*$/;
const MODEL_SELECTION_KEYS = ["model", "model_reasoning_effort", "reasoning_effort"] as const;


export class AgentRolePackagingError extends Error {}

export async function renderAgentRoles(repoRoot = defaultRepoRoot()): Promise<Map<string, string>> {
  const root = resolve(repoRoot);
  const spec = await readSpec(join(root, SPEC_PATH));
  const files = new Map<string, string>();
  const manifest: GeneratedAgentsManifest = {
    version: 1,
    nativeRoleAliases: spec.nativeRoleAliases,
    agents: [],
  };
  const seenAgentTypes = new Set<string>();

  for (const role of spec.roles) {
    const templatePath = join(root, TEMPLATE_PATH, `${role.behavior}.toml`);
    const template = await readFile(templatePath, "utf8").catch(() => {
      throw new AgentRolePackagingError(`Missing agent role template: ${templatePath}`);
    });
    const templateConfig = parseTemplate(template, templatePath);
    if (MODEL_SELECTION_KEYS.some((key) => Object.hasOwn(templateConfig, key))) {
      throw new AgentRolePackagingError(`Agent role template must not select model or reasoning: ${templatePath}`);
    }
    if (seenAgentTypes.has(role.behavior)) throw new AgentRolePackagingError(`Duplicate generated agent type: ${role.behavior}`);
    seenAgentTypes.add(role.behavior);
    const configFile = `${role.behavior}.toml`;
    files.set(configFile, [
      "# Generated by `bun run agents:build`; edit the role template or spec instead.",
      template.trim(),
      "",
    ].join("\n"));
    manifest.agents.push({
      agentType: role.behavior,
      behavior: role.behavior,
      description: role.description,
      configFile,
    });
  }

  for (const [alias, target] of Object.entries(spec.nativeRoleAliases)) {
    if (seenAgentTypes.has(alias)) {
      throw new AgentRolePackagingError(`Native role alias ${alias} collides with generated agent type`);
    }
    if (!seenAgentTypes.has(target)) {
      throw new AgentRolePackagingError(`Native role alias ${alias} targets unknown generated agent type ${target}`);
    }
  }
  files.set("manifest.json", `${JSON.stringify(manifest, null, 2)}\n`);
  return files;
}

export async function buildAgentRoles(repoRoot = defaultRepoRoot()): Promise<void> {
  const root = resolve(repoRoot);
  const destination = join(root, GENERATED_PATH);
  const files = await renderAgentRoles(root);
  await rm(destination, { force: true, recursive: true });
  await mkdir(destination, { recursive: true });
  await Promise.all([...files].map(([path, contents]) => writeFile(join(destination, path), contents)));
}

export async function checkAgentRoles(repoRoot = defaultRepoRoot()): Promise<void> {
  const root = resolve(repoRoot);
  const destination = join(root, GENERATED_PATH);
  const expected = await renderAgentRoles(root);
  const actualNames = await readdir(destination).catch(() => [] as string[]);
  const differences: string[] = [];
  for (const [path, contents] of expected) {
    const actual = await readFile(join(destination, path), "utf8").catch(() => undefined);
    if (actual === undefined) differences.push(`missing ${path}`);
    else if (actual !== contents) differences.push(`changed ${path}`);
  }
  for (const path of actualNames) {
    if (!expected.has(path)) differences.push(`unexpected ${path}`);
  }
  if (differences.length > 0) {
    throw new AgentRolePackagingError(
      `Generated agent roles diverge from their specification:\n${differences.map((line) => `- ${line}`).join("\n")}\nRun \`bun run agents:build\`.`,
    );
  }
}

async function readSpec(path: string): Promise<AgentRoleSpec> {
  const spec = JSON.parse(await readFile(path, "utf8")) as AgentRoleSpec;
  if (
    !isRecord(spec) ||
    spec.version !== 1 ||
    !isRecord(spec.nativeRoleAliases) ||
    !Array.isArray(spec.roles) || spec.roles.length === 0 ||
    Object.keys(spec).some(key => !["version", "nativeRoleAliases", "roles"].includes(key))
  ) {
    throw new AgentRolePackagingError(`Invalid agent role specification: ${path}`);
  }
  for (const [alias, target] of Object.entries(spec.nativeRoleAliases)) {
    assertIdentifier(alias, `native role alias ${alias}`);
    assertIdentifier(target, `native role alias target ${target}`);
  }
  const seenBehaviors = new Set<string>();
  for (const role of spec.roles) {
    if (!isRecord(role)) throw new AgentRolePackagingError(`Invalid role in ${path}`);
    assertIdentifier(role.behavior, `role behavior ${role.behavior}`);
    if (seenBehaviors.has(role.behavior)) throw new AgentRolePackagingError(`Duplicate role behavior: ${role.behavior}`);
    seenBehaviors.add(role.behavior);
    if (typeof role.description !== "string" || role.description.length === 0) {
      throw new AgentRolePackagingError(`Invalid description for role ${role.behavior}`);
    }
    if (Object.keys(role).some(key => !["behavior", "description"].includes(key))) {
      throw new AgentRolePackagingError(`Unknown field in role ${role.behavior}`);
    }
  }
  return spec;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function assertIdentifier(value: unknown, label: string): asserts value is string {
  if (typeof value !== "string" || !IDENTIFIER_PATTERN.test(value)) {
    throw new AgentRolePackagingError(`Invalid ${label}; expected a lowercase identifier`);
  }
}

function parseTemplate(template: string, path: string): Record<string, unknown> {
  try {
    return Bun.TOML.parse(template) as Record<string, unknown>;
  } catch {
    throw new AgentRolePackagingError(`Invalid agent role template TOML: ${path}`);
  }
}

function defaultRepoRoot(): string {
  return resolve(dirname(fileURLToPath(import.meta.url)), "../../..");
}

async function main(): Promise<void> {
  const command = process.argv[2];
  if (command === "build") await buildAgentRoles();
  else if (command === "check") await checkAgentRoles();
  else throw new AgentRolePackagingError("usage: bun packages/core/src/agent-role-package.ts <build|check>");
}

if (import.meta.main) {
  main().catch((error) => {
    console.error(error instanceof Error ? error.message : "agent role packaging failed");
    process.exit(1);
  });
}
